server:
  port: 8083

spring:
  application:
    name: api-gateway

  zipkin:
    base-url: http://localhost:9412
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: category-service
          uri: lb://CATEGORY
          predicates:
            - Path=/api/v1/categories/**, /api/v1/sub-categories/**

        - id: product
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**


        - id: vendor-service
          uri: lb://VENDOR-SERVICE
          predicates:
            - Path=/api/v1/vendors/**

        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/inventories/**

        - id: openapi
          uri: lb://API-GATEWAY
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs



springdoc:
  swagger-ui:
      urls:
        - name: category
          url: /v3/api-docs/category
        - name: product
          url: /v3/api-docs/product
        - name: vendor
          url: /v3/api-docs/vendor


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true