server:
  port: 8085

spring:
  application:
    name: category

  datasource:
    url: jdbc:postgresql://localhost:5433/edmart # to be changed to postgres:5432/astraworks
    username: edmart
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true
    generate-ddl: true

  zipkin:
    base-url: http://localhost:9412

  redis:
    host: localhost
    port: 6380
    database: 0
    timeout: 3600
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 2
        max-wait: -1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost



