/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.edmart.contracts.product;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class InventorySchemaEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3140241412179669986L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"InventorySchemaEvent\",\"namespace\":\"com.edmart.contracts.product\",\"fields\":[{\"name\":\"productId\",\"type\":\"long\"},{\"name\":\"quantity\",\"type\":\"int\"},{\"name\":\"productStatus\",\"type\":{\"type\":\"enum\",\"name\":\"ProductStatus\",\"symbols\":[\"ACTIVE\",\"INACTIVE\"]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<InventorySchemaEvent> ENCODER =
      new BinaryMessageEncoder<InventorySchemaEvent>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<InventorySchemaEvent> DECODER =
      new BinaryMessageDecoder<InventorySchemaEvent>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<InventorySchemaEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<InventorySchemaEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<InventorySchemaEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<InventorySchemaEvent>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this InventorySchemaEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a InventorySchemaEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a InventorySchemaEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static InventorySchemaEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private long productId;
   private int quantity;
   private com.edmart.contracts.product.ProductStatus productStatus;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public InventorySchemaEvent() {}

  /**
   * All-args constructor.
   * @param productId The new value for productId
   * @param quantity The new value for quantity
   * @param productStatus The new value for productStatus
   */
  public InventorySchemaEvent(java.lang.Long productId, java.lang.Integer quantity, com.edmart.contracts.product.ProductStatus productStatus) {
    this.productId = productId;
    this.quantity = quantity;
    this.productStatus = productStatus;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return productId;
    case 1: return quantity;
    case 2: return productStatus;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: productId = (java.lang.Long)value$; break;
    case 1: quantity = (java.lang.Integer)value$; break;
    case 2: productStatus = (com.edmart.contracts.product.ProductStatus)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'productId' field.
   * @return The value of the 'productId' field.
   */
  public long getProductId() {
    return productId;
  }


  /**
   * Sets the value of the 'productId' field.
   * @param value the value to set.
   */
  public void setProductId(long value) {
    this.productId = value;
  }

  /**
   * Gets the value of the 'quantity' field.
   * @return The value of the 'quantity' field.
   */
  public int getQuantity() {
    return quantity;
  }


  /**
   * Sets the value of the 'quantity' field.
   * @param value the value to set.
   */
  public void setQuantity(int value) {
    this.quantity = value;
  }

  /**
   * Gets the value of the 'productStatus' field.
   * @return The value of the 'productStatus' field.
   */
  public com.edmart.contracts.product.ProductStatus getProductStatus() {
    return productStatus;
  }


  /**
   * Sets the value of the 'productStatus' field.
   * @param value the value to set.
   */
  public void setProductStatus(com.edmart.contracts.product.ProductStatus value) {
    this.productStatus = value;
  }

  /**
   * Creates a new InventorySchemaEvent RecordBuilder.
   * @return A new InventorySchemaEvent RecordBuilder
   */
  public static com.edmart.contracts.product.InventorySchemaEvent.Builder newBuilder() {
    return new com.edmart.contracts.product.InventorySchemaEvent.Builder();
  }

  /**
   * Creates a new InventorySchemaEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new InventorySchemaEvent RecordBuilder
   */
  public static com.edmart.contracts.product.InventorySchemaEvent.Builder newBuilder(com.edmart.contracts.product.InventorySchemaEvent.Builder other) {
    if (other == null) {
      return new com.edmart.contracts.product.InventorySchemaEvent.Builder();
    } else {
      return new com.edmart.contracts.product.InventorySchemaEvent.Builder(other);
    }
  }

  /**
   * Creates a new InventorySchemaEvent RecordBuilder by copying an existing InventorySchemaEvent instance.
   * @param other The existing instance to copy.
   * @return A new InventorySchemaEvent RecordBuilder
   */
  public static com.edmart.contracts.product.InventorySchemaEvent.Builder newBuilder(com.edmart.contracts.product.InventorySchemaEvent other) {
    if (other == null) {
      return new com.edmart.contracts.product.InventorySchemaEvent.Builder();
    } else {
      return new com.edmart.contracts.product.InventorySchemaEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for InventorySchemaEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<InventorySchemaEvent>
    implements org.apache.avro.data.RecordBuilder<InventorySchemaEvent> {

    private long productId;
    private int quantity;
    private com.edmart.contracts.product.ProductStatus productStatus;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.edmart.contracts.product.InventorySchemaEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.productId)) {
        this.productId = data().deepCopy(fields()[0].schema(), other.productId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.quantity)) {
        this.quantity = data().deepCopy(fields()[1].schema(), other.quantity);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.productStatus)) {
        this.productStatus = data().deepCopy(fields()[2].schema(), other.productStatus);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing InventorySchemaEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.edmart.contracts.product.InventorySchemaEvent other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.productId)) {
        this.productId = data().deepCopy(fields()[0].schema(), other.productId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.quantity)) {
        this.quantity = data().deepCopy(fields()[1].schema(), other.quantity);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.productStatus)) {
        this.productStatus = data().deepCopy(fields()[2].schema(), other.productStatus);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'productId' field.
      * @return The value.
      */
    public long getProductId() {
      return productId;
    }


    /**
      * Sets the value of the 'productId' field.
      * @param value The value of 'productId'.
      * @return This builder.
      */
    public com.edmart.contracts.product.InventorySchemaEvent.Builder setProductId(long value) {
      validate(fields()[0], value);
      this.productId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'productId' field has been set.
      * @return True if the 'productId' field has been set, false otherwise.
      */
    public boolean hasProductId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'productId' field.
      * @return This builder.
      */
    public com.edmart.contracts.product.InventorySchemaEvent.Builder clearProductId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'quantity' field.
      * @return The value.
      */
    public int getQuantity() {
      return quantity;
    }


    /**
      * Sets the value of the 'quantity' field.
      * @param value The value of 'quantity'.
      * @return This builder.
      */
    public com.edmart.contracts.product.InventorySchemaEvent.Builder setQuantity(int value) {
      validate(fields()[1], value);
      this.quantity = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'quantity' field has been set.
      * @return True if the 'quantity' field has been set, false otherwise.
      */
    public boolean hasQuantity() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'quantity' field.
      * @return This builder.
      */
    public com.edmart.contracts.product.InventorySchemaEvent.Builder clearQuantity() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'productStatus' field.
      * @return The value.
      */
    public com.edmart.contracts.product.ProductStatus getProductStatus() {
      return productStatus;
    }


    /**
      * Sets the value of the 'productStatus' field.
      * @param value The value of 'productStatus'.
      * @return This builder.
      */
    public com.edmart.contracts.product.InventorySchemaEvent.Builder setProductStatus(com.edmart.contracts.product.ProductStatus value) {
      validate(fields()[2], value);
      this.productStatus = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'productStatus' field has been set.
      * @return True if the 'productStatus' field has been set, false otherwise.
      */
    public boolean hasProductStatus() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'productStatus' field.
      * @return This builder.
      */
    public com.edmart.contracts.product.InventorySchemaEvent.Builder clearProductStatus() {
      productStatus = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public InventorySchemaEvent build() {
      try {
        InventorySchemaEvent record = new InventorySchemaEvent();
        record.productId = fieldSetFlags()[0] ? this.productId : (java.lang.Long) defaultValue(fields()[0]);
        record.quantity = fieldSetFlags()[1] ? this.quantity : (java.lang.Integer) defaultValue(fields()[1]);
        record.productStatus = fieldSetFlags()[2] ? this.productStatus : (com.edmart.contracts.product.ProductStatus) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<InventorySchemaEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<InventorySchemaEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<InventorySchemaEvent>
    READER$ = (org.apache.avro.io.DatumReader<InventorySchemaEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.productId);

    out.writeInt(this.quantity);

    out.writeEnum(this.productStatus.ordinal());

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.productId = in.readLong();

      this.quantity = in.readInt();

      this.productStatus = com.edmart.contracts.product.ProductStatus.values()[in.readEnum()];

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.productId = in.readLong();
          break;

        case 1:
          this.quantity = in.readInt();
          break;

        case 2:
          this.productStatus = com.edmart.contracts.product.ProductStatus.values()[in.readEnum()];
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










