server:
  port: 8090

spring:
  application:
    name: inventory-service

  datasource:
    username: edmart
    driver-Class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/edmart-server
    password: password
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'


  zipkin:
    base-url: http://localhost:9412

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: inventory
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost

#management:
#  server:
#    port: 9101
#  endpoints:
#    web:
#      exposure:
#        include: health, prometheus
#      base-path: "/"
#      path-mapping:
#        prometheus: "metrics"
#  metrics:
#    tags:
#      application: transfer-service